export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const PENDING_CHARACTERS = 'PENDING_CHARACTERS';
export const REJECT_CHARACTERS = 'REJECT_CHARACTERS';

export const FETCH_SINGLECHARACTER = 'FETCH_SINGLECHARACTER';
export const PENDING_SINGLECHARACTER = 'PENDING_SINGLECHARACTER';
export const REJECT_SINGLECHARACTER = 'REJECT_SINGLECHARACTER';

export const CHANGE_PARAMS = 'CHANGE_PARAMS';
